AppBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        zip:
            type: string
            length: 255
        street:
            type: string
            length: 255
        streetnr:
            type: integer
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
        phonenumber:
            type: string
            length: 255
        pictureurl:
            type: string
            length: 255
        birthdate:
            type: datetime
    lifecycleCallbacks: {  }
